# Qdrant Vector Store Reaction for simple query
apiVersion: v1
kind: Reaction
name: sk-qdrant-simple-reaction
spec:
  kind: SyncSemanticKernelVectorStore
  queries:
    sk-qdrant-products-query: |
      {
        "collectionName": "qdrant_products_simple",
        "keyField": "id",
        "documentTemplate": "Product: {{name}} - {{description}}",
        "vectorField": "content_vector",
        "createCollection": true
      }
  properties:
    vectorStoreType: Qdrant
    connectionString: "Endpoint=http://qdrant.default.svc.cluster.local:6334"
    embeddingServiceType: AzureOpenAI
    embeddingEndpoint: "https://aman-eastus-resource.cognitiveservices.azure.com/"
    embeddingApiKey: "${AZURE_OPENAI_KEY}"
    embeddingModel: "text-embedding-3-large"
    embeddingDimensions: 3072
    distanceFunction: CosineSimilarity
    indexKind: Hnsw
    isFilterable: true
---
# Qdrant Vector Store Reaction for join query
apiVersion: v1
kind: Reaction
name: sk-qdrant-join-reaction
spec:
  kind: SyncSemanticKernelVectorStore
  queries:
    sk-qdrant-products-category-query: |
      {
        "collectionName": "qdrant_products_categories",
        "keyField": "product_id",
        "documentTemplate": "Product: {{product_name}} in {{category_name}}. {{product_description}}. Category: {{category_description}}",
        "vectorField": "content_vector",
        "createCollection": true
      }
  properties:
    vectorStoreType: Qdrant
    connectionString: "Endpoint=http://qdrant.default.svc.cluster.local:6334"
    embeddingServiceType: AzureOpenAI
    embeddingEndpoint: "https://aman-eastus-resource.cognitiveservices.azure.com/"
    embeddingApiKey: "${AZURE_OPENAI_KEY}"
    embeddingModel: "text-embedding-3-large"
    embeddingDimensions: 3072
    distanceFunction: CosineSimilarity
    indexKind: Hnsw
    isFilterable: true