apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333 # Qdrant HTTP API port
        - containerPort: 6334 # Qdrant gRPC port
        env:
        - name: QDRANT__STORAGE__STORAGE_PATH
          value: "/qdrant/storage"
        volumeMounts:
        - name: qdrant-storage
          mountPath: "/qdrant/storage"
      volumes:
      - name: qdrant-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    protocol: TCP
    port: 6333
    targetPort: 6333
  - name: grpc
    protocol: TCP
    port: 6334
    targetPort: 6334
  type: ClusterIP